#!/usr/bin/env bash
set -euo pipefail

mkdir -p build

c++ -std=c++17 -Wall -Wextra -Wpedantic -Iinclude \
  src/common/config.cpp \
  src/common/serialization.cpp \
  src/dashboard/dashboard_server.cpp \
  src/dashboard/status_json.cpp \
  src/storage/file_kv_engine.cpp \
  src/storage/kv_command.cpp \
  src/pd/metadata_store.cpp \
  src/pd/pd_server.cpp \
  src/pd/pd_service.cpp \
  src/pd/scheduler.cpp \
  src/region/region.cpp \
  src/raft/raft_node.cpp \
  src/raft/raft_storage.cpp \
  src/raft/snapshot.cpp \
  src/rpc/in_process_rpc.cpp \
  src/rpc/rpc_codec.cpp \
  src/rpc/tcp_rpc.cpp \
  src/gateway/route_cache.cpp \
  src/gateway/gateway_server.cpp \
  src/gateway/rpc_gateway_client.cpp \
  src/gateway/gateway_service.cpp \
  src/client/rstone_client.cpp \
  src/store/single_region_cluster.cpp \
  src/store/multi_region_cluster.cpp \
  src/store/distributed_region_node.cpp \
  src/store/store_service.cpp \
  src/main.cpp \
  -o build/rstone-server

c++ -std=c++17 -Wall -Wextra -Wpedantic -Iinclude \
  src/common/config.cpp \
  src/common/serialization.cpp \
  src/dashboard/dashboard_server.cpp \
  src/dashboard/status_json.cpp \
  src/storage/file_kv_engine.cpp \
  src/storage/kv_command.cpp \
  src/pd/metadata_store.cpp \
  src/pd/pd_server.cpp \
  src/pd/pd_service.cpp \
  src/pd/scheduler.cpp \
  src/region/region.cpp \
  src/raft/raft_node.cpp \
  src/raft/raft_storage.cpp \
  src/raft/snapshot.cpp \
  src/rpc/in_process_rpc.cpp \
  src/rpc/rpc_codec.cpp \
  src/rpc/tcp_rpc.cpp \
  src/gateway/route_cache.cpp \
  src/gateway/gateway_server.cpp \
  src/gateway/rpc_gateway_client.cpp \
  src/gateway/gateway_service.cpp \
  src/client/rstone_client.cpp \
  src/store/single_region_cluster.cpp \
  src/store/multi_region_cluster.cpp \
  src/store/distributed_region_node.cpp \
  src/store/store_service.cpp \
  tools/rstone_cli.cpp \
  -o build/rstone-cli

c++ -std=c++17 -Wall -Wextra -Wpedantic -Iinclude \
  src/common/config.cpp \
  src/common/serialization.cpp \
  src/dashboard/dashboard_server.cpp \
  src/dashboard/status_json.cpp \
  src/storage/file_kv_engine.cpp \
  src/storage/kv_command.cpp \
  src/pd/metadata_store.cpp \
  src/pd/pd_server.cpp \
  src/pd/pd_service.cpp \
  src/pd/scheduler.cpp \
  src/region/region.cpp \
  src/raft/raft_node.cpp \
  src/raft/raft_storage.cpp \
  src/raft/snapshot.cpp \
  src/rpc/in_process_rpc.cpp \
  src/rpc/rpc_codec.cpp \
  src/rpc/tcp_rpc.cpp \
  src/gateway/route_cache.cpp \
  src/gateway/gateway_server.cpp \
  src/gateway/rpc_gateway_client.cpp \
  src/gateway/gateway_service.cpp \
  src/client/rstone_client.cpp \
  src/store/single_region_cluster.cpp \
  src/store/multi_region_cluster.cpp \
  src/store/distributed_region_node.cpp \
  src/store/store_service.cpp \
  tests/unit/test_main.cpp \
  tests/unit/status_test.cpp \
  tests/unit/config_test.cpp \
  tests/unit/serialization_test.cpp \
  tests/unit/status_json_test.cpp \
  tests/unit/file_kv_engine_test.cpp \
  tests/unit/pd_metadata_store_test.cpp \
  tests/unit/pd_server_test.cpp \
  tests/unit/pd_service_test.cpp \
  tests/unit/scheduler_test.cpp \
  tests/unit/raft_node_test.cpp \
  tests/unit/raft_storage_test.cpp \
  tests/unit/snapshot_test.cpp \
  tests/unit/rpc_test.cpp \
  tests/unit/rpc_codec_test.cpp \
  tests/unit/tcp_rpc_test.cpp \
  tests/unit/gateway_server_test.cpp \
  tests/unit/multi_region_gateway_test.cpp \
  tests/unit/rpc_gateway_client_test.cpp \
  tests/unit/gateway_service_test.cpp \
  tests/unit/tcp_gateway_e2e_test.cpp \
  tests/unit/client_test.cpp \
  tests/unit/single_region_cluster_test.cpp \
  tests/unit/multi_region_cluster_test.cpp \
  tests/unit/store_service_test.cpp \
  -o build/rstone_unit_tests_manual
